-- Users Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    age INTEGER,
    locale VARCHAR(255),
    sso_qualifier VARCHAR(255)
);

-- Posts Table
CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    content VARCHAR(255),
    title VARCHAR(255),
    user_id BIGINT NOT NULL
);

-- Comments Table
CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    content VARCHAR(255),
    post_id BIGINT,
    user_id BIGINT NOT NULL
);

-- Lotto Spot Table
CREATE TABLE lotto_spot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    address VARCHAR(255),
    first_place_wins INTEGER,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    name VARCHAR(255),
    second_place_wins INTEGER
);

-- Lotto Ticket Table
CREATE TABLE lotto_ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    ordinal INTEGER NOT NULL,
    status SMALLINT,
    url VARCHAR(255),
    user_id BIGINT NOT NULL
);

-- Lotto Game Table
CREATE TABLE lotto_game (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    number1 INTEGER NOT NULL,
    number2 INTEGER NOT NULL,
    number3 INTEGER NOT NULL,
    number4 INTEGER NOT NULL,
    number5 INTEGER NOT NULL,
    number6 INTEGER NOT NULL,
    status SMALLINT,
    ticket_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    lotto_ticket_id BIGINT
);

-- Foreign Keys (Optional but recommended)
ALTER TABLE comments ADD CONSTRAINT fk_comments_posts FOREIGN KEY (post_id) REFERENCES posts (id);
ALTER TABLE lotto_game ADD CONSTRAINT fk_lotto_game_ticket FOREIGN KEY (lotto_ticket_id) REFERENCES lotto_ticket (id);
